In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

**Data collec**

In [7]:
df=pd.read_csv("/content/emails.csv")

In [8]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [9]:
df["spam"].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

**Duplicate remove**

In [10]:
df.duplicated().sum()

np.int64(33)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df["spam"].value_counts()

spam
0    4327
1    1368
Name: count, dtype: int64

In [13]:
df.isnull().sum()

text    0
spam    0
dtype: int64

**Separate x and y**

In [14]:
x= df.text.values
y= df.spam.values

**split dataset**

In [15]:
xtrain, xtest, ytrain, ytest=train_test_split(x,y, test_size=0.2, random_state=42)

**Text Preprocessing**

In [16]:
cv=CountVectorizer()
x_train=cv.fit_transform(xtrain)

In [17]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**ML Algorithms**

In [18]:
mb=MultinomialNB()

In [19]:
model=mb.fit(x_train, ytrain)

In [20]:
model.score(x_train, ytrain)

0.9964881474978051

In [21]:
x_test=cv.transform(xtest)

In [22]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [2, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
model.score(x_test, ytest)

0.9912203687445127

**model testing**

In [44]:
emails=["If you're not seeing your Spam or Trash, go to the bottom of your label list on the left, click More,  then scroll again until you find them ", "I have successfully submitted my assignment for the Machine Learning course."]

In [45]:
test=cv.transform(emails)


In [46]:
test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [47]:
model.predict(test)

array([1, 0])

**Save Model**

In [50]:
import pickle as pk

In [51]:
pk.dump(model,open("model1","wb"))

In [53]:
import os
os.getcwd()

'/content'

In [54]:
model2=pk.load(open("model1","rb"))

In [57]:
model2.predict(test)

array([1, 0])